# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2026 Franz X. Mohr

# Writes test/dees2007_us.h, the US country model of Dees, di Mauro, Pesaran and
# Smith (2007) as the bgvars package sets it up, for unit_coint_dees_us.cpp.
#
#   OUT=test Rscript test/make_dees2007_us.R
#
# Needs bgvars and bvartools. Not run by the build: the header is committed.

suppressPackageStartupMessages(library(bgvars))
data("dees2007")
sd <- dees2007$submodel_data; g <- dees2007$global_data
v <- c(colnames(sd$US$endogen), "poil"); sd$US$endogen <- cbind(sd$US$endogen, g); colnames(sd$US$endogen) <- v
obj <- add_weight_matrices(create_gvecmodel(sd), sd, period = 1999:2001)
obj$submodels$US <- create_vecxsubmodel(obj, "US", endogen = c("y","Dp","rs","rl","q","poil"), p_endogen = 2,
  exogen = c("y","Dp","ep"), p_exogen = 3, r = 2, const = "unrestricted", trend = "restricted",
  iterations = 10, burnin = 10)
obj <- scale_error_correction(obj)
obj <- add_priors(obj, coef = list(v_i = 0), coint = list(v_i = 0, p_tau_i = 1), sigma = list(df = 3, scale = 1e-4))
obj <- add_initial_values(obj)
m <- obj$submodels$US[[1]]
y <- unclass(m$data$train$y); w <- unclass(m$data$train$w); x <- unclass(m$data$train$x)
cat("dims y", dim(y), " w", dim(w), " x", dim(x), " a", length(m$initial$a), " beta", length(m$initial$beta),
    " tsp", tsp(m$data$train$y), "\n")
cat("w:", colnames(w), "\nx:", colnames(x), "\ny:", colnames(y), "\n")
cat("scale:", attr(m$data$train$w, "scale"), "\n")
fmt <- function(name, mat, comment) {
  vals <- sprintf("%.17g", as.vector(t(mat)))  # row-major: one period per row
  lines <- split(vals, ceiling(seq_along(vals) / 4))
  c(paste0("// ", comment),
    sprintf("constexpr double %s[%d] = {", name, length(vals)),
    paste0("    ", vapply(lines, paste, character(1), collapse = ", "), ","),
    "};", "")
}
out <- c("// SPDX-License-Identifier: BSD-3-Clause",
         "// Copyright (c) 2026 Franz X. Mohr",
         "",
         "// The US country model of Dees, di Mauro, Pesaran and Smith (2007), as the",
         "// bgvars package sets it up from its dees2007 data set. Generated by",
         "// test/make_dees2007_us.R; do not edit by hand.",
         "//",
         "// Table B9 of the paper: VARX*(2, 2) with rank 2, an unrestricted constant and",
         "// a trend restricted to the cointegration space. Endogenous: output, inflation,",
         "// the short and long rate, equity prices and the oil price. Weakly exogenous:",
         "// foreign output, inflation and the exchange rate, with trade weights over",
         "// 1999-2001. Sample 1979Q4-2003Q4. Every series of the error correction term is",
         "// divided by the standard deviation of its differences, the trend by its own",
         "// (bgvars::scale_error_correction), and the starting values are the reduced",
         "// rank maximum likelihood estimates on that scale.",
         "",
         "#ifndef BAYESTS_TEST_DEES2007_US_H",
         "#define BAYESTS_TEST_DEES2007_US_H",
         "",
         "namespace dees2007_us",
         "{",
         "",
         sprintf("constexpr int kTT = %d;", nrow(y)),
         sprintf("constexpr int kK = %d;", ncol(y)),
         sprintf("constexpr int kKBeta = %d;", ncol(w)),
         sprintf("constexpr int kNX = %d;", ncol(x)),
         sprintf("constexpr int kRank = %d;", m$model$rank),
         sprintf("constexpr int kP = %d;", m$model$p_endogen),
         "",
         paste0("// y: ", paste(colnames(y), collapse = " ")),
         paste0("// w: ", paste(colnames(w), collapse = " ")),
         paste0("// x: ", paste(colnames(x), collapse = " ")),
         "",
         fmt("kY", y, "Differences, kTT x kK, one period per row."),
         fmt("kW", w, "Error correction term, kTT x kKBeta, one period per row."),
         fmt("kX", x, "Short-run regressors, kTT x kNX, one period per row."),
         fmt("kInitialA", matrix(m$initial$a, 1), "Starting loadings and short-run coefficients, vec of kK x (kRank + kNX)."),
         fmt("kInitialBeta", matrix(m$initial$beta, 1), "Starting cointegration vectors, vec of kKBeta x kRank."),
         fmt("kInitialSigmaInv", matrix(as.vector(m$initial$u_sigma_inv), 1), "Starting error precision, vec of kK x kK."),
         "} // namespace dees2007_us", "", "#endif")
writeLines(out, file.path(Sys.getenv("OUT"), "dees2007_us.h"))
cat("written\n")
